version: '3.4'
services:
  bitcoin.avado.dnp.dappnode.eth:
    image: 'bitcoin.avado.dnp.dappnode.eth:10.0.5'
    build:
      context: ./build
      args:
        VERSION: 0.21.0
    volumes:
      - 'bitcoin_data:/root/.bitcoin'
    ports:
      - '8333:8333'
      - '18332:18332'
      - '18333:18333'
      - '28332:28332'
      - '28333:28333'
    environment:
      - BTC_RPCUSER=avado
      - BTC_RPCPASSWORD=avado
      - BTC_TXINDEX=1
      - BTC_PRUNE=0
      - BTC_TESTNET=0
    restart: always
volumes:
  bitcoin_data: {}
